# Generated by Django 4.1.6 on 2023-02-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_ngo_address_alter_ngo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philanthropist',
            name='tax_exception_perc',
            field=models.IntegerField(null=True),
        ),
    ]
