# Generated by Django 4.1.6 on 2023-02-11 13:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_philanthropist_tax_exception_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='primary_cause',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Child welfare'), (2, 'Education'), (3, 'Special needs'), (4, 'Healthcare'), (5, 'Women welfare')], max_length=200, null=True),
        ),
    ]
