# Generated by Django 4.1.6 on 2023-02-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_baseuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='philanthropist',
            old_name='name',
            new_name='state',
        ),
    ]
