# Generated by Django 4.1.6 on 2023-02-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_name_philanthropist_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
