# Generated by Django 4.1.6 on 2023-02-11 21:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ngo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='review_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='philanthropist',
            name='primary_cause',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Child welfare'), (2, 'Education'), (3, 'Special needs'), (4, 'Healthcare'), (5, 'Women welfare')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='philanthropist',
            name='trust_score',
            field=models.FloatField(null=True),
        ),
    ]
