# Generated by Django 4.1.6 on 2023-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_tax_exception_perc_philanthropist_fund_contrib_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='fund_received',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='trust_score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='philanthropist',
            name='fund_contrib',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='philanthropist',
            name='trust_score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
