# Generated by Django 4.1.6 on 2023-02-11 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_alter_ngo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('location_of_work', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('site_url', models.CharField(default='', max_length=300, null=True)),
                ('onsite_remote', models.CharField(blank=True, default='Remote', max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('job_description', models.TextField()),
                ('skills_required', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ngo')),
            ],
        ),
    ]
