# Generated by Django 4.1.6 on 2023-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='job_description',
            new_name='event_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_of_work',
        ),
        migrations.RemoveField(
            model_name='event',
            name='onsite_remote',
        ),
        migrations.RemoveField(
            model_name='event',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='event',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='event',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fund_raised',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fund_required',
            field=models.IntegerField(null=True),
        ),
    ]
