# Generated by Django 4.1.6 on 2023-02-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_rename_job_description_event_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fund_raised',
            new_name='funds_raised',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fund_required',
            new_name='funds_required',
        ),
    ]
