# Generated by Django 4.1.6 on 2023-02-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_alter_event_funds_raised_alter_event_funds_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='perc',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
